### ISSUE TITLE
Transfer ownership of @norpan repo instead of forking

### ISSUE THREAD

**Issue by ringods** [matheus23/elm-language-server#11]
I noticed that this repo in the `elm-tooling` organization is forked from @norpan. Would it be possible to transfer the ownership of the @norpan repo to this organization? I bumped into similar cases with other projects too. When searching github for code or issues, I experienced the original (outdated) repository popping up in the search results along with the the organization fork. For users, this could be confusing. 

Therefor, I would like to ask for a few more cycles in the setup:
* merge all changed code back to the @norpan origin.
* disable CI of this fork
* delete this forked repo
* [transfer the ownership](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-to-an-organization) of the @norpan repo to this organization
* re-enable CI of the transferred repo.

Advantage of ownership transfer is that any web links to the @norpan repo will be redirected to the organization now. Only drawback is that you loose the issues from this existing fork. But I guess better now than later.

**Comment by norpan** [comment]
Fine by me! Just tell me what to do :)

**Comment by norpan** [comment]
I deleted my repo, so this is now the main repo!

**Comment by razzeee** [comment]
can you do the same for https://github.com/norpan/elm-vscode-language-client ?

**Comment by norpan** [comment]
Done!
