### ISSUE TITLE
Getting Started (not working / help wanted)

### ISSUE THREAD

**Issue by janwirth** [matheus23/elm-language-server#15]
Sorry - rookie question.

I am using `elm-language-server` with `kakoune-lsp`.

I downloaded and installed `elm-language-server` using stack.

And nothing happens afterwards. It just stays like this. 

In my `kak-lsp.toml` I put
```
[language.elm]
filetypes = ["elm"]
roots = ["elm.json"]
command = "elm-language-server"
```

When I open an elm file and try to use lsp features like go to definition it does not do anything.

Now when I start the server I see

```
❯ elm-language-server  
2019-01-10 21:40:47.35797303 [ThreadId 11] - 




haskell-lsp:Starting up server ...

```

How can I make sure the server is at all operational and not stuck?

Any hot tips on how to get this to work?

**Comment by razzeee** [comment]
Only thing this can do right now is diagnostics, so break something in your app and if the compiler fails you should get those messages in your ide

**Comment by janwirth** [comment]
You recommend vscode or which particular battle-tested setup?

**Comment by razzeee** [comment]
In general or to test this?

**Comment by janwirth** [comment]
To test this. I am planning to integrate this with mawww/kakoune.

**Comment by razzeee** [comment]
I'm using vscode but compiling this is just commandline. https://github.com/elm-tooling/elm-language-server#building

Not sure this is helping.

**Comment by janwirth** [comment]
As mentioned, I already compiled using stack etc (I have used haskell before) I'll try to hook it up to vscode then.

**Comment by razzeee** [comment]
You've seen this? https://github.com/elm-tooling/elm-vscode-language-client

**Comment by matheus23** [comment]
We test the lsp using what @Razzeee linked.

Clone the repo and open it using vscode. Press F5, while having the elm-language-server in PATH, open any project that has an elm.json file and the Server should report diagnostics :)

Let me know if there are any issues!

**Comment by janwirth** [comment]
Great - it works.

I would love to have it work with kakoune though. I will report back if I am make progress.
